// flow-typed signature: 826c78091cd2cebc75e53ab9deaa6875
// flow-typed version: <<STUB>>/oauth2-server_v2.4.x/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oauth2-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oauth2-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oauth2-server/examples/dynamodb/dal' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/dynamodb/index' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/dynamodb/model' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/memory/model' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/mongodb/model' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/postgresql/index' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/postgresql/model' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/redis/index' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/redis/model' {
  declare module.exports: any;
}

declare module 'oauth2-server/examples/redis/testData' {
  declare module.exports: any;
}

declare module 'oauth2-server/lib/authCodeGrant' {
  declare module.exports: any;
}

declare module 'oauth2-server/lib/authorise' {
  declare module.exports: any;
}

declare module 'oauth2-server/lib/error' {
  declare module.exports: any;
}

declare module 'oauth2-server/lib/grant' {
  declare module.exports: any;
}

declare module 'oauth2-server/lib/oauth2server' {
  declare module.exports: any;
}

declare module 'oauth2-server/lib/runner' {
  declare module.exports: any;
}

declare module 'oauth2-server/lib/token' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/authCodeGrant' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/authorise' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/error' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/errorHandler' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/grant.authorization_code' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/grant.client_credentials' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/grant.extended' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/grant' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/grant.password' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/grant.refresh_token' {
  declare module.exports: any;
}

declare module 'oauth2-server/test/lockdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oauth2-server/examples/dynamodb/dal.js' {
  declare module.exports: $Exports<'oauth2-server/examples/dynamodb/dal'>;
}
declare module 'oauth2-server/examples/dynamodb/index.js' {
  declare module.exports: $Exports<'oauth2-server/examples/dynamodb/index'>;
}
declare module 'oauth2-server/examples/dynamodb/model.js' {
  declare module.exports: $Exports<'oauth2-server/examples/dynamodb/model'>;
}
declare module 'oauth2-server/examples/memory/model.js' {
  declare module.exports: $Exports<'oauth2-server/examples/memory/model'>;
}
declare module 'oauth2-server/examples/mongodb/model.js' {
  declare module.exports: $Exports<'oauth2-server/examples/mongodb/model'>;
}
declare module 'oauth2-server/examples/postgresql/index.js' {
  declare module.exports: $Exports<'oauth2-server/examples/postgresql/index'>;
}
declare module 'oauth2-server/examples/postgresql/model.js' {
  declare module.exports: $Exports<'oauth2-server/examples/postgresql/model'>;
}
declare module 'oauth2-server/examples/redis/index.js' {
  declare module.exports: $Exports<'oauth2-server/examples/redis/index'>;
}
declare module 'oauth2-server/examples/redis/model.js' {
  declare module.exports: $Exports<'oauth2-server/examples/redis/model'>;
}
declare module 'oauth2-server/examples/redis/testData.js' {
  declare module.exports: $Exports<'oauth2-server/examples/redis/testData'>;
}
declare module 'oauth2-server/lib/authCodeGrant.js' {
  declare module.exports: $Exports<'oauth2-server/lib/authCodeGrant'>;
}
declare module 'oauth2-server/lib/authorise.js' {
  declare module.exports: $Exports<'oauth2-server/lib/authorise'>;
}
declare module 'oauth2-server/lib/error.js' {
  declare module.exports: $Exports<'oauth2-server/lib/error'>;
}
declare module 'oauth2-server/lib/grant.js' {
  declare module.exports: $Exports<'oauth2-server/lib/grant'>;
}
declare module 'oauth2-server/lib/oauth2server.js' {
  declare module.exports: $Exports<'oauth2-server/lib/oauth2server'>;
}
declare module 'oauth2-server/lib/runner.js' {
  declare module.exports: $Exports<'oauth2-server/lib/runner'>;
}
declare module 'oauth2-server/lib/token.js' {
  declare module.exports: $Exports<'oauth2-server/lib/token'>;
}
declare module 'oauth2-server/test/authCodeGrant.js' {
  declare module.exports: $Exports<'oauth2-server/test/authCodeGrant'>;
}
declare module 'oauth2-server/test/authorise.js' {
  declare module.exports: $Exports<'oauth2-server/test/authorise'>;
}
declare module 'oauth2-server/test/error.js' {
  declare module.exports: $Exports<'oauth2-server/test/error'>;
}
declare module 'oauth2-server/test/errorHandler.js' {
  declare module.exports: $Exports<'oauth2-server/test/errorHandler'>;
}
declare module 'oauth2-server/test/grant.authorization_code.js' {
  declare module.exports: $Exports<'oauth2-server/test/grant.authorization_code'>;
}
declare module 'oauth2-server/test/grant.client_credentials.js' {
  declare module.exports: $Exports<'oauth2-server/test/grant.client_credentials'>;
}
declare module 'oauth2-server/test/grant.extended.js' {
  declare module.exports: $Exports<'oauth2-server/test/grant.extended'>;
}
declare module 'oauth2-server/test/grant.js' {
  declare module.exports: $Exports<'oauth2-server/test/grant'>;
}
declare module 'oauth2-server/test/grant.password.js' {
  declare module.exports: $Exports<'oauth2-server/test/grant.password'>;
}
declare module 'oauth2-server/test/grant.refresh_token.js' {
  declare module.exports: $Exports<'oauth2-server/test/grant.refresh_token'>;
}
declare module 'oauth2-server/test/lockdown.js' {
  declare module.exports: $Exports<'oauth2-server/test/lockdown'>;
}
